name: eliza-assistant
region: nyc
services:
  - name: web
    dockerfile_path: Dockerfile
    github:
      branch: main
      deploy_on_push: true
    http_port: 8080
    routes:
      - path: /
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    instance_count: 1
    instance_size_slug: basic-xs
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8080"
      - key: ELIZA_DB_PATH
        value: /data/db
      - key: PM2_PUBLIC_KEY
        scope: RUN_TIME
        value: ""
      - key: PM2_SECRET_KEY
        scope: RUN_TIME
        value: "" 